import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nicholas Bortz's Portfolio</title>
        <meta name="Nicholas Bortz's Portfolio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1>
          Portfolio
        </h1>

    
      </main>
    </div>
  )
}
